@extends('app')

@section('content')

<div class="row">
    <div class="col-12 text-center p-5 pmclr">
        <h2>CGV</h2>
    </div>
</div>

<div class="row">
    <div class="col-12 pmclr p-3 p-md-5">
    <h1><strong><span style="font-size:18pt;">CONDITIONS G&Eacute;N&Eacute;RALES DE VENTE</span></strong></h1>
<p><span style="font-size:12pt;">&nbsp;</span><strong><span style="font-size:12pt;">Article 1- Champ d&rsquo;application et objet des conditions g&eacute;n&eacute;rales de vente</span></strong></p>
<p><span style="font-size:12pt;">Les pr&eacute;sentes Conditions G&eacute;n&eacute;rales de Vente d&eacute;crivent le service de commande en ligne de la gamme de produits disponibles dans les restaurants CENTRAL SUSHI participants et accessible via le site&nbsp;www.central-sushi.fr</span></p>
<p><span style="font-size:12pt;">Les pr&eacute;sentes Conditions G&eacute;n&eacute;rales de Vente (ci-apr&egrave;s les &laquo; CGV &raquo;) s&rsquo;appliquent &agrave; toute commande (ci-apr&egrave;s &laquo; Commande &raquo;) d&rsquo;un ou plusieurs produits (ci-apr&egrave;s le ou les &laquo; Produit(s) &raquo;) pass&eacute;e par l&rsquo;acheteur (ci-apr&egrave;s le &laquo; Client &raquo;) sur le site marchand www.central-sushi.fr (ci-apr&egrave;s le &laquo; Site &raquo;), &eacute;dit&eacute; par la soci&eacute;t&eacute; CENTRAL SUSHI COMPANY (ci-apr&egrave;s &laquo; l&rsquo;Editeur &raquo;), aupr&egrave;s de l&rsquo;un des Restaurants sous enseigne CENTRAL SUSHI participant (ci-apr&egrave;s le &laquo; Vendeur &raquo;, le &laquo; Restaurant &raquo;).</span></p>
<p><span style="font-size:12pt;">Les pr&eacute;sentes conditions g&eacute;n&eacute;rales de vente a distance r&eacute;gissent la relation contractuelle entre d&rsquo;une part, les restaurants du r&eacute;seau central sushi, franchis&eacute;s ind&eacute;pendants ou filiales du groupe central sushi, repr&eacute;sent&eacute;s aux fins des pr&eacute;sent&eacute;s par central sushi Company, SAS au capital de 5000 euros ( RCS Besancon n&deg;847 711 322), sise 6 rue Simone Michel Levy- 25000 Besancon ( ci-apr&egrave;s CENTRAL SUSHI) et d&rsquo;autre part, chaque client ( ci-apr&egrave;s le ou les clients) passant commande par t&eacute;l&eacute;phone ou via le site internet &agrave; l&rsquo;adresse&nbsp;</span><a href="http://www.centralsushi.fr"><u><span style="color:#0563c1;font-size:12pt;">http://www.centralsushi.fr</span></u></a><span style="font-size:12pt;">.</span></p>
<p><span style="font-size:12pt;">La commande en ligne sur le Site est r&eacute;serv&eacute;e aux Clients &acirc;g&eacute;s d&rsquo;au moins 13 ans &agrave; la date de passation de la commande.</span></p>
<p><span style="font-size:12pt;">Le Vendeur se r&eacute;serve le droit de modifier les CGV &agrave; tout moment sans pr&eacute;avis. Ces modifications sont applicables et opposable au client &agrave; compter de leur mise en ligne sur le site et s&rsquo;appliquent a toutes commande post&eacute;rieur. Les CGV applicables seront celles figurant sur le Site &agrave; la date de la Commande par le Client.</span></p>
<p><span style="font-size:12pt;">&nbsp;</span><strong><span style="font-size:12pt;">Article 2 - D&eacute;finitions</span></strong></p>
<p><span style="font-size:12pt;">Dans les pr&eacute;sentes CGV, les mots ou expressions suivants auront les significations suivantes :</span><span style="font-size:12pt;"><br></span><span style="font-size:12pt;">&nbsp;-Les termes le &laquo; Vendeur &raquo; et le &laquo; Restaurant &raquo; d&eacute;signent la soci&eacute;t&eacute; d&rsquo;exploitation du Restaurant sous enseigne CENTRAL SUSHI s&eacute;lectionn&eacute; par le Client et aupr&egrave;s de laquelle la commande sera enregistr&eacute;e et dont les coordonn&eacute;es seront indiqu&eacute;es sur l&rsquo;email confirmant la commande et sur le ticket de caisse d&eacute;livr&eacute; dans le Restaurant participant lors du retrait ou de la livraison des Produits.</span><span style="font-size:12pt;"><br></span><span style="font-size:12pt;">- Le terme &laquo; Commande &raquo; d&eacute;signe le service, mis &agrave; disposition par l&rsquo;Editeur, et l&rsquo;ensemble du processus de commande en ligne de produits disponibles dans les Restaurants participants. Le Client effectue le paiement de sa commande en ligne, &agrave; la livraison ou au moment du retrait des produits</span></p>
<p><strong><span style="font-size:12pt;">1. &nbsp; &nbsp; &nbsp;Acceptation des CGV</span></strong></p>
<p><span style="font-size:12pt;">Le Client d&eacute;clare avoir pris connaissance et accept&eacute; les pr&eacute;sentes CGV avant la passation de sa Commande. Toute Commande d&rsquo;un Produit sur le Site mat&eacute;rialise donc de la part du Client l&rsquo;acceptation expresse des pr&eacute;sentes CGV.</span></p>
<p><strong><span style="font-size:12pt;">2. &nbsp; &nbsp; &nbsp;Les Produits</span></strong></p>
<p><span style="font-size:12pt;">Les produits propos&eacute;s par le Restaurant choisi par le Client sont ceux qui figurent dans le catalogue publi&eacute; sur le Site le jour de la Commande, dans la limite toutefois des stocks disponibles. Il est recommand&eacute; de consommer sous 24 heures les produits &agrave; compter de leur retrait en Restaurant, et de les conserver au frais.&nbsp;</span></p>
<p><span style="font-size:12pt;">Il est recommand&eacute; de ne jamais les congeler les produits.</span></p>
<p><span style="font-size:12pt;">Les produits pr&eacute;sent&eacute;s &agrave; la vente sont susceptibles d&rsquo;&ecirc;tre modifi&eacute;s ou supprim&eacute;s par le Vendeur sans aucun pr&eacute;avis. Les photographies et illustrations pr&eacute;sent&eacute;es en ligne ne sont pas contractuelles.</span></p>
<p><span style="font-size:12pt;">&nbsp;</span></p>
<p><strong><span style="font-size:12pt;">3. &nbsp; &nbsp;Cr&eacute;ation d&rsquo;un compte</span></strong></p>
<p><span style="font-size:12pt;">La prise de commande via le site suppose une inscription en vue de la cr&eacute;ation d&rsquo;un compte client Central sushi. A cet effet le client remplit un formulaire d&rsquo;inscription disponible directement sur le site, choisit un identifiant associ&eacute; &agrave; une adresse de courrier &eacute;lectronique valide et un mot de passe.&nbsp;</span></p>
<p><span style="font-size:12pt;">Il s&rsquo;engage &agrave; garder ces informations strictement confidentielles et &agrave; ne pas les communiquer &agrave; des tiers, afin d&rsquo;&eacute;viter autant que possible tout risque d&rsquo;intrusion dans son compte client.&nbsp;</span></p>
<p><span style="font-size:12pt;">CENTRAL SUSHI ne pourra &ecirc;tre tenu responsable d&rsquo;aucune utilisation non autoris&eacute;e du compte client par un tiers qui aurait eu acc&egrave;s &agrave; l&rsquo;identifiant et au mot de passe, s&rsquo;ils ont &eacute;t&eacute; communiqu&eacute;s &agrave; un tiers par le client ou en raison de sa n&eacute;gligence.&nbsp;</span></p>
<p><span style="font-size:12pt;">Lors de son inscription, le Client choisit un identifiant et un mot de passe auxquels il associe ses nom / pr&eacute;noms, date de naissance, une adresse postale pr&eacute;cise (num&eacute;ro de b&acirc;timent, d&rsquo;&eacute;tage, digicode), num&eacute;ro de t&eacute;l&eacute;phone.&nbsp;</span></p>
<p><span style="font-size:12pt;">L&rsquo;adresse de livraison indiqu&eacute;e doit &ecirc;tre aussi pr&eacute;cise que possible afin de permettre une livraison dans les meilleures conditions. CENTRAL SUSHI ne pourra &ecirc;tre tenu responsable en cas d&rsquo;impossibilit&eacute; de livraison due &agrave; des renseignements erron&eacute;s ou incomplets.&nbsp;</span></p>
<p><span style="font-size:12pt;">&Agrave; la suite de la cr&eacute;ation du compte client, Le client aura &agrave; la possibilit&eacute;, via son espace, d&rsquo;acc&eacute;der &agrave; l&rsquo;historique de ses commandes et de proc&eacute;der &agrave; toutes modifications concernant les informations qu&rsquo;il a transmis.&nbsp;</span></p>
<p><span style="font-size:12pt;">Le client a toutefois la possibilit&eacute; de passer une commande sans cr&eacute;ation d&rsquo;un compte client , en tant &laquo; qu&rsquo;invit&eacute; &raquo;. Les informations tels que son nom, pr&eacute;nom, adresse et num&eacute;ro de t&eacute;l&eacute;phone seront utilis&eacute;es dans le cadre de l&rsquo;ex&eacute;cution de sa commande mais ne seront pas m&eacute;moris&eacute;es, ni enregistr&eacute;es.&nbsp;</span></p>
<p><strong><span style="font-size:12pt;">ARTICLE 3 &ndash; COMMANDE&nbsp;</span></strong></p>
<p><strong><span style="font-size:12pt;">1 &nbsp; &nbsp; &nbsp; Proc&eacute;dure de passation de Commande</span></strong></p>
<p><span style="font-size:12pt;">&nbsp;</span></p>
<p><span style="font-size:12pt;">Le client choisi entre les modes de mise a disposition de la commande en cliquant sur les onglets &laquo;&nbsp;livraison&nbsp;&raquo; ou &laquo; &agrave; emporter&nbsp;&raquo; sur le site.</span></p>
<p><span style="font-size:12pt;">Si le client choisi la livraison, le client est invit&eacute; &agrave; entrer son code postal ou son adresse postale, situ&eacute; dans la zone de livraison de l&rsquo;un des restaurants CENTRAL SUSHI, afin d&rsquo;&ecirc;tre redirig&eacute; vers celui-ci..&nbsp;</span></p>
<p><span style="font-size:12pt;">&Agrave; d&eacute;faut un message l&rsquo;informera qu&rsquo;il est situ&eacute; en dehors de l&rsquo;une des zones de livraison et lui proposera de venir r&eacute;cup&eacute;rer sa commande &agrave; emporter, dans le cas o&ugrave; l&rsquo;adresse indiqu&eacute;e se situe en dehors de la zone de livraison desservie par le restaurant CENTRAL SUSHI.&nbsp;</span></p>
<p><span style="font-size:12pt;">Dans le cas de la vente &agrave; emporter, une liste d&eacute;roulante lui permettra de s&eacute;lectionner le restaurant de son choix. &nbsp;</span></p>
<p><span style="font-size:12pt;">Une fois le restaurant d&eacute;termin&eacute;, le client peut commencer &agrave; effectuer sa commande en s&eacute;lectionnant les produits qu&rsquo;il souhaite. Il ajoute ainsi les produits &agrave; son panier.&nbsp;</span></p>
<p><span style="font-size:12pt;">Il a la possibilit&eacute; de choisir le nombre de sauces, baguettes, suppl&eacute;ment de wasabi et gingembre.</span></p>
<p><span style="font-size:12pt;">La validation finale de la Commande entraine l&rsquo;acceptation par le Client des pr&eacute;sentes CGV, la reconnaissance d&rsquo;en avoir parfaite connaissance et la renonciation &agrave; se pr&eacute;valoir de ses propres conditions d&rsquo;achat ou de toutes autres conditions.</span></p>
<p><span style="font-size:12pt;">Par la suite le Client a la possibilit&eacute; de se connecter &agrave; son compte via ses propres identifiants ou choisir de commander en tant qu&rsquo;&nbsp;&laquo;&nbsp;invit&eacute;&nbsp;&raquo; tel qu&rsquo;&eacute;nonc&eacute; au paragraphe 3 &laquo; Cr&eacute;ation de compte&nbsp;&raquo;.</span></p>
<p><span style="font-size:12pt;">Un bref r&eacute;capitulatif de sa commande et des informations que le Client a renseign&eacute; selon le mode de livraison choisi lui permettra de v&eacute;rifier l&rsquo;exactitude des informations saisies.&nbsp;</span></p>
<p><span style="font-size:12pt;">L&rsquo;&eacute;tape suivante consiste &agrave; choisir le mode de paiement de la commande. Le Client aura la possibilit&eacute; de choisir un paiement par carte bancaire sur le site web via un dispositif s&eacute;curis&eacute;e, en esp&egrave;ces, titres restaurant et carte bancaire aupr&egrave;s du livreur pour les commandes en livraison, ou un paiement directement au restaurant pour les commandes &agrave; emporter.&nbsp;</span></p>
<p><span style="font-size:12pt;">S&rsquo;il d&eacute;cide de choisir le service de retrait de sa commande, il appartient au Client de v&eacute;rifier les heures de fermeture du Restaurant sur la page du Restaurant qu&rsquo;il aura s&eacute;lectionn&eacute; afin d&rsquo;op&eacute;rer le dit retrait pendant les heures d&rsquo;ouverture du restaurant s&eacute;lectionn&eacute;.</span></p>
<p><span style="font-size:12pt;">Une page de confirmation de commande apparait apr&egrave;s avoir finalis&eacute; le mode de paiement de la commande. Un email de confirmation sera envoy&eacute; sur la boite mail du Client, selon l&rsquo;adresse mail qu&rsquo;il aura fourni.</span></p>
<ol start="2">
    <li style="list-style-type:decimal;font-size:12pt;">
        <p><strong><span style="font-size:12pt;">&nbsp; Preuve de la Commande</span></strong></p>
    </li>
</ol>
<p><span style="font-size:12pt;">La validation finale de la Commande vaudra preuve de l&rsquo;int&eacute;gralit&eacute; de ladite Commande et vaudra exigibilit&eacute; des sommes engag&eacute;es par la Commande.</span></p>
<p><span style="font-size:12pt;">Les registres informatis&eacute;s du Vendeur, conserv&eacute;s dans les syst&egrave;mes informatiques du Vendeur ou de son prestataire back office dans des conditions raisonnables de s&eacute;curit&eacute;, seront consid&eacute;r&eacute;s par le Vendeur et le Client comme preuve des communications, des commandes, des paiements et des transactions intervenus entre les parties.</span></p>
<p><span style="font-size:12pt;">&nbsp;</span></p>
<ol start="3">
    <li style="list-style-type:decimal;font-size:12pt;">
        <p><strong><span style="font-size:12pt;">&nbsp; &nbsp; &nbsp; Droit de r&eacute;tractation&nbsp;</span></strong></p>
    </li>
</ol>
<p><span style="font-size:12pt;">Conform&eacute;ment aux dispositions de l&rsquo;article L221-28-4 du Code de la Consommation, le droit de r&eacute;tractation applicable en mati&egrave;re de vente &agrave; distance ne peut &ecirc;tre exerc&eacute; dans le cas de la fourniture de biens qui du fait de leur nature sont susceptibles de se d&eacute;t&eacute;riorer ou de se p&eacute;rimer rapidement.</span></p>
<p><span style="font-size:12pt;">En application de ce texte, il est express&eacute;ment indiqu&eacute; que toute Commande sur le Site est ferme et d&eacute;finitive et que l&rsquo;exercice du droit de r&eacute;tractation est exclu.</span></p>
<p><span style="font-size:12pt;">Les Commandes qui ont donc &eacute;t&eacute; d&eacute;finitivement valid&eacute;es ne sont pas annulables. Aucune marchandise ne peut &ecirc;tre reprise ou &eacute;chang&eacute;e.</span></p>
<ol start="4">
    <li style="list-style-type:decimal;font-size:12pt;">
        <p><strong><span style="font-size:12pt;">&nbsp; &nbsp;Retrait ou livraison des Produits</span></strong></p>
    </li>
</ol>
<p><span style="font-size:12pt;">Le retrait des Produits dans le Restaurant ne peut se faire qu&rsquo;&agrave; partir de l&rsquo;heure d&rsquo;ouverture du restaurant s&eacute;lectionn&eacute; et avant l&rsquo;heure de fermeture du Restaurant qu&rsquo;il aura pr&eacute;alablement s&eacute;lectionn&eacute; ou l&rsquo;heure de fermeture du service de retrait fix&eacute; par le Restaurant s&eacute;lectionn&eacute;.</span></p>
<p><span style="font-size:12pt;">Les horaires du service de commande en ligne, ainsi que les horaires d&rsquo;ouverture du Restaurant o&ugrave; le Client souhaite retirer sa Commande sont disponibles sur le Site au moment o&ugrave; le Client s&eacute;lectionne ledit Restaurant.</span></p>
<p><span style="font-size:12pt;">Le Client ne pourra retirer ses Produits qu&rsquo;en se munissant de son num&eacute;ro de Commande figurant sur la confirmation de Commande qui pourra prendre la forme d&rsquo;un Email ou un SMS de confirmation.</span></p>
<p><span style="font-size:12pt;">Une fois la commande valid&eacute;e, la livraison intervient dans un d&eacute;lai g&eacute;n&eacute;ralement de trente (30) &agrave; quarante-cinq (45) minutes, sous r&eacute;serve de variations dues &agrave; un flux important de commandes et sous r&eacute;serve d&rsquo;un cas de force majeure telle que d&eacute;fini par la jurisprudence. Tout d&eacute;lai est donc mentionn&eacute; &agrave; titre indicatif et n&rsquo;est pas contractuel.</span></p>
<p><span style="font-size:12pt;">Le d&eacute;lai de retrait pour les commandes effectu&eacute;es &agrave; emporter est d&rsquo;environ quinze (15) &agrave; vingt (20) minutes.</span></p>
<p><strong><span style="font-size:12pt;">Article 4 -RECLAMATIONS</span></strong></p>
<p><span style="font-size:12pt;">Toute question ou r&eacute;clamation concernant les Produits retir&eacute;s en Restaurants ou livr&eacute;s devra &ecirc;tre faite dans un d&eacute;lai maximum de vingt-quatre (24) heures apr&egrave;s le retrait ou la livraison desdits Produits, aupr&egrave;s du Vendeur, par courrier, &agrave; l&rsquo;adresse figurant sur le ticket de caisse et sur l&rsquo;email de confirmation envoy&eacute; lors de toute Commande. Pass&eacute; ce d&eacute;lai, aucune question ni aucune r&eacute;clamation ne pourra &ecirc;tre prise en compte.</span></p>
<p><span style="font-size:12pt;">Pour toute question relative &agrave; l&rsquo;ex&eacute;cution du contrat, le client peut contacter le service client CENTRAL SUSHI via le formulaire de contact dans la rubrique &laquo; Contactez-nous &raquo; disponible sur le site ou via le num&eacute;ro de t&eacute;l&eacute;phone du restaurant en question.&nbsp;</span></p>
<p><strong><span style="font-size:12pt;">Article 5 &ndash; PRIX&nbsp;</span></strong></p>
<p><span style="font-size:12pt;">Les prix applicables sont ceux en vigueur au moment de la commande du client, tels qu&rsquo;affich&eacute;s sur le site.&nbsp;</span></p>
<p><span style="font-size:12pt;">Les prix figurants sur les pages de Commande en ligne du Site sont des prix TTC (toutes taxes comprises) en euro tenant compte de la TVA applicable au jour de la Commande.</span></p>
<p><span style="font-size:12pt;">Le Vendeur se r&eacute;serve le droit de modifier ses prix &agrave; tous moments et sans aucun pr&eacute;avis, &eacute;tant toutefois entendu que le prix figurant au catalogue le jour de la Commande sera le seul applicable.</span></p>
<p><span style="font-size:12pt;">Des frais de traitement pour toute commande en ligne pass&eacute;e sur le site www.central-sushi.fr peuvent &ecirc;tre factur&eacute;s en sus pour un montant forfaitaire de 0.95 &euro;TTC. Ces frais suppl&eacute;mentaires sont indiqu&eacute;s dans le r&eacute;capitulatif de commande sous le libell&eacute; &laquo; frais de gestion &raquo;.</span></p>
<p><strong><span style="font-size:12pt;">ARTICLE 6 - &nbsp; Modalit&eacute;s de paiement de la Commande</span></strong></p>
<p><span style="font-size:12pt;">Les Commandes effectu&eacute;es sur le Site sont payables par carte bancaire directement sur le site internet, ou soit en esp&egrave;ce ou en ticket restaurant lors de la livraison ou du retrait en restaurant.&nbsp;</span></p>
<p><span style="font-size:12pt;">Les commandes doivent &ecirc;tre pay&eacute;s en int&eacute;gralit&eacute;.&nbsp;</span></p>
<p><span style="font-size:12pt;">Les paiements par carte bancaire sont r&eacute;alis&eacute;s par le biais d&rsquo;un syst&egrave;me fiable et s&eacute;curis&eacute; de paiement qui garantit la pr&eacute;servation du caract&egrave;re confidentiel des num&eacute;ros de carte bancaire par des proc&eacute;dures de protection et de cryptologie.</span></p>
<p><strong><span style="font-size:12pt;">ARTICLE 7 - Responsabilit&eacute;</span></strong></p>
<p><span style="font-size:12pt;">L&rsquo;Editeur s&rsquo;engage &agrave; assurer un acc&egrave;s au service de prise de commande en ligne optimal. Toutefois, l&rsquo;Editeur ne sera pas tenu d&rsquo;assurer le fonctionnement du site Internet www.central-sushi.fr&nbsp;ni du service de prise de commande en cas de force majeure telle que d&eacute;finie par la jurisprudence.</span></p>
<p><span style="font-size:12pt;">L&rsquo;Editeur d&eacute;cline en outre toute responsabilit&eacute; en cas d&rsquo;interruption du site Internet www.central-sushi.fr , de survenance de bugs ou d&rsquo;erreurs de fonctionnement, ainsi qu&rsquo;en cas de dommages, directs ou indirects, qu&rsquo;elles qu&rsquo;en soient les causes, origines, natures ou cons&eacute;quences, provoqu&eacute;s &agrave; raison de l&rsquo;acc&egrave;s de quiconque au site Internet www.central-sushi.fr &nbsp;ou de l&rsquo;impossibilit&eacute; d&rsquo;y acc&eacute;der, y compris les risques inh&eacute;rents &agrave; l&rsquo;utilisation du r&eacute;seau Internet tel que perte de donn&eacute;es, intrusion, virus, rupture du service ou tout autre risque assimil&eacute;.</span></p>
<p><span style="font-size:12pt;">Les informations pr&eacute;sentes sur le site Internet www.central-sushi.fr&nbsp;sont mentionn&eacute;es &agrave; titre purement indicatif, sous r&eacute;serve d&rsquo;erreur ou d&rsquo;omission.</span></p>
<p><span style="font-size:12pt;">La responsabilit&eacute; de l&rsquo;Editeur ou du Vendeur ne saurait &ecirc;tre engag&eacute;e si l&rsquo;inex&eacute;cution ou la mauvaise ex&eacute;cution d&rsquo;une commande est imputable au client ou &agrave; des contraintes techniques ind&eacute;pendantes de la volont&eacute; de l&rsquo;Editeur ou du Vendeur. L&rsquo;Editeur et le Vendeur ne sauraient notamment &ecirc;tre tenus pour responsables, des dommages de toute nature tant mat&eacute;riels qu&rsquo;immat&eacute;riels qui pourraient r&eacute;sulter d&rsquo;une mauvaise utilisation de l&rsquo;identifiant ou du mode op&eacute;ratoire de passation de commande, du retard, de la perte ou de la mauvaise distribution d&rsquo;un email, d&rsquo;un sms, notamment de confirmation de commande, ni de son envoi ou non &agrave; une adresse &eacute;lectronique ou un num&eacute;ro de t&eacute;l&eacute;phone erron&eacute;.</span></p>
<p><span style="font-size:12pt;">Le Client est inform&eacute; que l&rsquo;Editeur peut s&rsquo;appuyer sur les comp&eacute;tences d&rsquo;un prestataire ext&eacute;rieur pour g&eacute;rer notamment l&rsquo;ensemble de son back office et le paiement s&eacute;curis&eacute; des commandes en ligne. Le Client s&rsquo;engage &agrave; ne jamais rechercher la responsabilit&eacute; de l&rsquo;Editeur et &agrave; agir directement aupr&egrave;s de ce prestataire en cas de litige survenu notamment &agrave; l&rsquo;occasion de l&rsquo;utilisation du module de paiement s&eacute;curis&eacute;. L&rsquo;Editeur fera tous ses meilleurs efforts pour que l&rsquo;adresse mail &agrave; laquelle contacter le prestataire soit disponible et facilement accessible.</span></p>
<p><strong><span style="font-size:12pt;">Article 8 - Garantie</span></strong></p>
<p><span style="font-size:12pt;">CENTRAL SUSHI s&rsquo;engage &agrave; ce que les produits livr&eacute;s soient conformes &agrave; la commande enregistr&eacute;e.&nbsp;</span></p>
<p><span style="font-size:12pt;">En cas de produit manquant ou non conforme, le client devra imm&eacute;diatement informer CENTRAL SUSHI lors de la livraison ou du retrait en restaurant, et au plus tard dans les 24 heures &agrave; compter de la livraison ou de la mise &agrave; disposition, &agrave; d&eacute;faut de quoi aucune r&eacute;clamation ne sera accept&eacute;e.&nbsp;</span></p>
<p><span style="font-size:12pt;">Les dispositions l&eacute;gales relatives &agrave; la garantie due en cas de vices cach&eacute;s (article 1641 et suivants du Code civil) et &agrave; la garantie de conformit&eacute; (articles L. 217-3 et suivants du Code de la consommation) s&apos;appliquent et sont reproduits int&eacute;gralement au sein de l&rsquo;article 9.</span></p>
<p><strong><span style="font-size:12pt;">Article 9 - Propri&eacute;t&eacute; Intellectuelle &nbsp;</span></strong></p>
<p><span style="font-size:12pt;">La structure g&eacute;n&eacute;rale du Site, l&rsquo;ensemble des &eacute;l&eacute;ments de toute nature contenus sur le Site, comprenant notamment les logiciels, structures de la/les base(s) de donn&eacute;es, photographies, visuels, vid&eacute;ographies, textes, dessins, images fixes ou anim&eacute;es, sons, graphismes, logos sont la propri&eacute;t&eacute; exclusive de CENTRAL SUSHI ou, le cas &eacute;ch&eacute;ant, de leurs propri&eacute;taires respectifs dont CENTRAL SUSHI a obtenu pr&eacute;alablement les autorisations d&rsquo;exploitation et sont prot&eacute;g&eacute;s par des droits de propri&eacute;t&eacute; intellectuelle.&nbsp;</span></p>
<p><span style="font-size:12pt;">Le Client, ou toute autre personne, s&apos;interdit notamment, de mani&egrave;re non exhaustive, pour un usage autre que priv&eacute;, de reproduire et/ou repr&eacute;senter, t&eacute;l&eacute;charger, vendre, distribuer, &eacute;mettre, traduire, adapter, exploiter, distribuer, diffuser et communiquer, int&eacute;gralement ou partiellement, sous quelque forme que ce soit, &agrave; titre commercial ou non, toute &oelig;uvre de l&rsquo;esprit originale ou contenu figurant sur le Site. A d&eacute;faut, le Client s&rsquo;expose &agrave; des poursuites judiciaires</span></p>
<p><strong><span style="font-size:12pt;">ARTICLE 10 - Donn&eacute;es personnelles&nbsp;</span></strong></p>
<p><span style="font-size:12pt;">Dans le cadre de son activit&eacute; CENTRAL SUSHI est amen&eacute; &agrave; collecter et &agrave; traiter des donn&eacute;es &agrave; caract&egrave;re personnel.</span></p>
<p><span style="font-size:12pt;">Les donn&eacute;es personnelles collect&eacute;es sur le Site sont n&eacute;cessaires au traitement de la commande et pourront &ecirc;tre communiqu&eacute;es aux partenaires du Mandataire sur acceptation expresse du Client.</span></p>
<p><span style="font-size:12pt;">Conform&eacute;ment &agrave; la Loi Informatique et Libert&eacute;s du 6 janvier 1978, le Client dispose d&rsquo;un droit d&rsquo;acc&egrave;s et de rectification des donn&eacute;es personnelles le concernant, et le Client peut s&rsquo;opposer &agrave; la communication de ces donn&eacute;es &agrave; des tiers. L&rsquo;exercice de ces droits est &agrave; effectuer aupr&egrave;s de : CENTRAL SUSHI COMPANY, avec un justificatif de votre identit&eacute; (photocopie d&rsquo;une pi&egrave;ce d&rsquo;identit&eacute;).</span></p>
<p><strong><span style="font-size:12pt;">Article 11 - Indivisibilit&eacute;</span></strong></p>
<p><span style="font-size:12pt;">La nullit&eacute; d&rsquo;une des clauses du pr&eacute;sent contrat en application notamment d&rsquo;une loi, d&rsquo;un r&egrave;glement ou &agrave; la suite d&rsquo;une d&eacute;cision de justice n&rsquo;entrainera pas la nullit&eacute; des pr&eacute;sentes CGV.</span></p>
<p><strong><span style="font-size:12pt;">Article 12- &nbsp; R&egrave;glement des litiges</span></strong></p>
<p><span style="font-size:12pt;">Les pr&eacute;sentes CGV sont soumises au droit fran&ccedil;ais.&nbsp;</span></p>
<p><span style="font-size:12pt;">Tous les litiges auxquels les pr&eacute;sentes conditions g&eacute;n&eacute;rales de vente pourraient donner lieu seront soumis aux tribunaux comp&eacute;tents dans les conditions de droit commun.&nbsp;</span></p>
<p><span style="font-size:12pt;">En cas de litige avec un client professionnel le tribunal de commerce de Besan&ccedil;on sera seul comp&eacute;tent.&nbsp;</span></p>
<p><span style="font-size:12pt;">En cas de litige, le Client est invit&eacute; &agrave; s&rsquo;adresse en priorit&eacute; au Vendeur CENTRAL SUSHI afin de trouver une solution amiable.&nbsp;</span></p>
<p><strong><span style="font-size:12pt;">Article 13 - Annexe&nbsp;</span></strong></p>
<p><strong><span style="font-size:12pt;">Article L217- 3</span></strong><span style="font-size:12pt;">&nbsp;</span><strong><span style="font-size:12pt;">du code de la consommation :</span></strong><span style="font-size:12pt;">&nbsp;&laquo; Le vendeur d&eacute;livre un bien conforme au contrat ainsi qu&apos;aux crit&egrave;res &eacute;nonc&eacute;s &agrave; l&apos;article L. 217-5. Il r&eacute;pond des d&eacute;fauts de conformit&eacute; existant au moment de la d&eacute;livrance du bien au sens de l&apos;article L. 216-1, qui apparaissent dans un d&eacute;lai de deux ans &agrave; compter de celle-ci. Article L217-4 du Code de la Consommation : Le bien est conforme au contrat s&apos;il r&eacute;pond notamment, le cas &eacute;ch&eacute;ant, aux crit&egrave;res suivants :</span></p>
<p><span style="font-size:12pt;">&nbsp;1&deg; Il correspond &agrave; la description, au type, &agrave; la quantit&eacute; et &agrave; la qualit&eacute;, notamment en ce qui concerne la fonctionnalit&eacute;, la compatibilit&eacute;, l&apos;interop&eacute;rabilit&eacute;, ou toute autres caract&eacute;ristiques pr&eacute;vues au contrat ;&nbsp;</span></p>
<p><span style="font-size:12pt;">2&deg; Il est propre &agrave; tout usage sp&eacute;cial recherch&eacute; par le consommateur, port&eacute; &agrave; la connaissance du vendeur au plus tard au moment de la conclusion du contrat et que ce dernier a accept&eacute; ;&nbsp;</span></p>
<p><span style="font-size:12pt;">3&deg; Il est d&eacute;livr&eacute; avec tous les accessoires et les instructions d&apos;installation, devant &ecirc;tre fournis conform&eacute;ment au contrat ;&nbsp;</span></p>
<p><span style="font-size:12pt;">4&deg; Il est mis &agrave; jour conform&eacute;ment au contrat.&nbsp;</span></p>
<p><strong><span style="font-size:12pt;">Article L217-5</span></strong><span style="font-size:12pt;">&nbsp;</span><strong><span style="font-size:12pt;">du code de la consommation</span></strong><span style="font-size:12pt;">&nbsp;: I.-En plus des crit&egrave;res de conformit&eacute; au contrat, le bien est conforme s&apos;il r&eacute;pond aux crit&egrave;res suivants :&nbsp;</span></p>
<p><span style="font-size:12pt;">1&deg; Il est propre &agrave; l&apos;usage habituellement attendu d&apos;un bien de m&ecirc;me type, compte tenu, s&apos;il y a lieu, de toute disposition du droit de l&apos;Union europ&eacute;enne et du droit national ainsi que de toutes les normes techniques ou, en l&apos;absence de telles normes techniques, des codes de conduite sp&eacute;cifiques applicables au secteur concern&eacute; ;&nbsp;</span></p>
<p><span style="font-size:12pt;">2&deg; Le cas &eacute;ch&eacute;ant, il poss&egrave;de les qualit&eacute;s que le vendeur a pr&eacute;sent&eacute;es au consommateur sous forme d&apos;&eacute;chantillon ou de mod&egrave;le, avant la conclusion du contrat ;&nbsp;</span></p>
<p><span style="font-size:12pt;">3&deg; Le cas &eacute;ch&eacute;ant, les &eacute;l&eacute;ments num&eacute;riques qu&apos;il comporte sont fournis selon la version la plus r&eacute;cente qui est disponible au moment de la conclusion du contrat, sauf si les parties en conviennent autrement ;&nbsp;</span></p>
<p><span style="font-size:12pt;">4&deg; Le cas &eacute;ch&eacute;ant, il est d&eacute;livr&eacute; avec tous les accessoires, y compris l&apos;emballage, et les instructions d&apos;installation que le consommateur peut l&eacute;gitimement attendre ;&nbsp;</span></p>
<p><span style="font-size:12pt;">5&deg; Le cas &eacute;ch&eacute;ant, il est fourni avec les mises &agrave; jour que le consommateur peut l&eacute;gitimement attendre, conform&eacute;ment aux dispositions de l&apos;article L. 217-19 ;&nbsp;</span></p>
<p><span style="font-size:12pt;">6&deg; Il correspond &agrave; la quantit&eacute;, &agrave; la qualit&eacute; et aux autres caract&eacute;ristiques, y compris en termes de durabilit&eacute;, de fonctionnalit&eacute;, de compatibilit&eacute; et de s&eacute;curit&eacute;, que le consommateur peut l&eacute;gitimement attendre pour des biens de m&ecirc;me type, eu &eacute;gard &agrave; la nature du bien ainsi qu&apos;aux d&eacute;clarations publiques faites par le vendeur, par toute personne en amont dans la cha&icirc;ne de transactions, ou par une personne agissant pour leur compte, y compris dans la publicit&eacute; ou sur l&apos;&eacute;tiquetage.</span></p>
<p><span style="font-size:12pt;">&nbsp;II.-Toutefois, le vendeur n&apos;est pas tenu par toutes d&eacute;clarations publiques mentionn&eacute;es &agrave; l&apos;alin&eacute;a qui pr&eacute;c&egrave;de s&apos;il d&eacute;montre :&nbsp;</span></p>
<p><span style="font-size:12pt;">1&deg; Qu&apos;il ne les connaissait pas et n&apos;&eacute;tait l&eacute;gitimement pas en mesure de les conna&icirc;tre ;&nbsp;</span></p>
<p><span style="font-size:12pt;">2&deg; Qu&apos;au moment de la conclusion du contrat, les d&eacute;clarations publiques avaient &eacute;t&eacute; rectifi&eacute;es dans des conditions comparables aux d&eacute;clarations initiales ;&nbsp;</span></p>
<p><span style="font-size:12pt;">Ou 3&deg; Que les d&eacute;clarations publiques n&apos;ont pas pu avoir d&apos;influence sur la d&eacute;cision d&apos;achat.&nbsp;</span></p>
<p><span style="font-size:12pt;">III.-Le consommateur ne peut contester la conformit&eacute; en invoquant un d&eacute;faut concernant une ou plusieurs caract&eacute;ristiques particuli&egrave;res du bien, dont il a &eacute;t&eacute; sp&eacute;cifiquement inform&eacute; qu&apos;elles s&apos;&eacute;cartaient des crit&egrave;res de conformit&eacute; &eacute;nonc&eacute;s au pr&eacute;sent article, &eacute;cart auquel il a express&eacute;ment et s&eacute;par&eacute;ment consenti lors de la conclusion du contrat. Article L217-6 :Lorsqu&apos;&agrave; l&apos;occasion du contrat, un traitement de donn&eacute;es &agrave; caract&egrave;re personnel est op&eacute;r&eacute; par le professionnel, un manquement de sa part aux obligations lui incombant au titre du r&egrave;glement (UE) 2016/679 du 27 avril 2016 et de la loi n&deg; 78- 17 du 6 janvier 1978 relative &agrave; l&apos;informatique, aux fichiers et aux libert&eacute;s, d&egrave;s lors que ce manquement entra&icirc;ne le non-respect d&apos;un ou de plusieurs crit&egrave;res de conformit&eacute; &eacute;nonc&eacute;s &agrave; la pr&eacute;sente section, est assimil&eacute; &agrave; un d&eacute;faut de conformit&eacute;, sans pr&eacute;judice des autres recours pr&eacute;vus par ces textes.&nbsp;</span></p>
<p><strong><span style="font-size:12pt;">Article L217-7 du code de la consommation</span></strong><span style="font-size:12pt;">&nbsp;: Les d&eacute;fauts de conformit&eacute; qui apparaissent dans un d&eacute;lai de vingt-quatre mois &agrave; compter de la d&eacute;livrance du bien, y compris du bien comportant des &eacute;l&eacute;ments num&eacute;riques, sont, sauf preuve contraire, pr&eacute;sum&eacute;s exister au moment de la d&eacute;livrance, &agrave; moins que cette pr&eacute;somption ne soit incompatible avec la nature du bien ou du d&eacute;faut invoqu&eacute;. Pour les biens d&apos;occasion, ce d&eacute;lai est fix&eacute; &agrave; douze mois. Lorsque le contrat de vente d&apos;un bien comportant des &eacute;l&eacute;ments num&eacute;riques pr&eacute;voit la fourniture continue d&apos;un contenu num&eacute;rique ou d&apos;un service num&eacute;rique, sont pr&eacute;sum&eacute;s exister au moment de la d&eacute;livrance du bien les d&eacute;fauts de conformit&eacute; qui apparaissent :&nbsp;</span></p>
<p><span style="font-size:12pt;">1&deg; Durant un d&eacute;lai de deux ans &agrave; compter de la d&eacute;livrance du bien, lorsque le contrat pr&eacute;voit cette fourniture pendant une dur&eacute;e inf&eacute;rieure ou &eacute;gale &agrave; deux ans ou lorsque le contrat ne d&eacute;termine pas la dur&eacute;e de fourniture ;&nbsp;</span></p>
<p><span style="font-size:12pt;">2&deg; Durant la p&eacute;riode durant laquelle le contenu num&eacute;rique ou le service num&eacute;rique est fourni en vertu du contrat, lorsque celui-ci pr&eacute;voit cette fourniture pendant une dur&eacute;e sup&eacute;rieure &agrave; deux ans. &raquo; En cas de d&eacute;faut de conformit&eacute;, le consommateur a droit &agrave; la mise en conformit&eacute; du bien par r&eacute;paration ou remplacement ou, &agrave; d&eacute;faut, &agrave; la r&eacute;duction du prix ou &agrave; la r&eacute;solution du contrat, dans les conditions &eacute;nonc&eacute;es dans les articles L217-8 &agrave; L217- 17 du Code de la Consommation.</span></p>
<p><strong><span style="font-size:12pt;">Article L221-28-4 du code de la consommation</span></strong><span style="font-size:12pt;">&nbsp;dispose &laquo; le droit de r&eacute;tractation ne peut pas &ecirc;tre exerc&eacute; pour les contrats : de fourniture de bien susceptibles de se d&eacute;t&eacute;riorer ou de se p&eacute;rimer rapidement &raquo;</span></p>
<p><strong><span style="font-size:12pt;">Article 1641 du code civil</span></strong><span style="font-size:12pt;">&nbsp;&laquo; le vendeur est tenu de la garantie a raison des d&eacute;fauts cach&eacute;s de la chose vendue qui la rendent impropre &agrave; l&rsquo;usage auquel on la destine ou qui diminuent tellement cet usage que l&rsquo;acheteur ne l&rsquo;aurait pas acquise, ou n&rsquo;en aurait donn&eacute; qu&rsquo;un moindre prix, s&rsquo;il les avait connus.&nbsp;</span></p>
<p><strong><span style="font-size:12pt;">Article 1642 du code civil&nbsp;</span></strong><span style="font-size:12pt;">: &laquo; le vendeur n&rsquo;est pas tenu des vices apparents et dont l&rsquo;acheteur et dont l&rsquo;acheteur a pu se convaincre lui-m&ecirc;me &raquo;&nbsp;</span></p>
<p><strong><span style="font-size:12pt;">Article 1643 du code civil</span></strong><span style="font-size:12pt;">&nbsp;: &laquo; Il est tenu des vices cach&eacute;s, quand m&ecirc;me il ne les aurait pas connus, &agrave; moins que, dans ce cas, il n&rsquo;a stipul&eacute; qu&rsquo;il ne sera oblig&eacute; &agrave; aucune garantie &raquo;</span></p>
<p><strong><span style="font-size:12pt;">Article 1644 du code civil</span></strong><span style="font-size:12pt;">&nbsp;: &laquo; Dans le cas des article 1641 et 1643, l&rsquo;acheteur a le choix de rendre la chose et se faire restituer le prix, ou de garder la chose et se faire rendre une partie du prix. &raquo;</span></p>
<p><strong><span style="font-size:12pt;">Article 1645 du code civil</span></strong><span style="font-size:12pt;">&nbsp;: &laquo; si le vendeur connaissait les vices de la chose, il est tenu, outre la restitution du prix qu&rsquo;il en recu, de tous les dommages et int&eacute;r&ecirc;ts envers l&rsquo;acheteur &raquo;</span></p>
<p><strong><span style="font-size:12pt;">Article 1646 du code civil</span></strong><span style="font-size:12pt;">&nbsp;&laquo; si le vendeur ignorait les vices de la chose, il ne sera tenu qu&rsquo;a la restitution du prix, et &agrave; rembourser &agrave; l&rsquo;acqu&eacute;reur les frais occasionn&eacute;s par la vente &raquo;&nbsp;</span></p>
<p><span style="font-size:12pt;">Date de la derni&egrave;re mise &agrave; jour le 30/11/2023</span></p>

    </div>
</div>

</section>

@endsection